version: "3.7"
services:
  database:
    image: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5431:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: "redis:alpine"
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    depends_on:
      - database
      - redis
    networks:
      - default
    ports:
      - "5555:5555"