// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Exchanger is an autogenerated mock type for the Exchanger type
type Exchanger struct {
	mock.Mock
}

// ConvertRubles provides a mock function with given fields: amount, currency
func (_m *Exchanger) ConvertRubles(amount float32, currency string) (float32, error) {
	ret := _m.Called(amount, currency)

	var r0 float32
	if rf, ok := ret.Get(0).(func(float32, string) float32); ok {
		r0 = rf(amount, currency)
	} else {
		r0 = ret.Get(0).(float32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(float32, string) error); ok {
		r1 = rf(amount, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
