// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RateRepository is an autogenerated mock type for the RateRepository type
type RateRepository struct {
	mock.Mock
}

// GetRubleRate provides a mock function with given fields: currency
func (_m *RateRepository) GetRubleRate(currency string) (float32, error) {
	ret := _m.Called(currency)

	var r0 float32
	if rf, ok := ret.Get(0).(func(string) float32); ok {
		r0 = rf(currency)
	} else {
		r0 = ret.Get(0).(float32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
