// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "avito-intership/models"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// ChangeBalance provides a mock function with given fields: userId, amount, productId
func (_m *Repository) ChangeBalance(userId int64, amount float32, productId int64) error {
	ret := _m.Called(userId, amount, productId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, float32, int64) error); ok {
		r0 = rf(userId, amount, productId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: userId
func (_m *Repository) GetBalance(userId int64) (float32, error) {
	ret := _m.Called(userId)

	var r0 float32
	if rf, ok := ret.Get(0).(func(int64) float32); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(float32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields: userId, page, perPage, sort, desc
func (_m *Repository) GetHistory(userId int64, page int64, perPage int64, sort int, desc bool) ([]*models.Transaction, error) {
	ret := _m.Called(userId, page, perPage, sort, desc)

	var r0 []*models.Transaction
	if rf, ok := ret.Get(0).(func(int64, int64, int64, int, bool) []*models.Transaction); ok {
		r0 = rf(userId, page, perPage, sort, desc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, int64, int64, int, bool) error); ok {
		r1 = rf(userId, page, perPage, sort, desc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferMoney provides a mock function with given fields: srcUserId, dstUserId, amount
func (_m *Repository) TransferMoney(srcUserId int64, dstUserId int64, amount float32) error {
	ret := _m.Called(srcUserId, dstUserId, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, float32) error); ok {
		r0 = rf(srcUserId, dstUserId, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
